version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: aps_image_processing
    volumes:
      - ./postgres:/var/lib/postgresql/data
