name: Deploy application to server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build application
    runs-on: ubuntu-20.04
    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: (front-end) Build front-end app
        run: |
          cd web
          yarn install
          yarn build

      - name: (back-end) Build back-end app
        run: |
          cd api
          yarn install
          yarn build

      - name: Deploy to host
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: -rltgoDzvO
          SOURCE: ./
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}

      - name: (front-end) Move build to target folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mv /root/apps/projects/aps/web/dist /var/www/html/aps
